version: '3'

services:
  
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: translaterr

  redis:
    image: redis:latest
    ports:
      - 6379:6379
