version: '3'

services:
  
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=translaterr
      - MSSQL_PID=Express
