version: '3'

services:
  
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tr4nsl4t3rr
      - MSSQL_PID=Express

  redis:
    image: redis:latest
    ports:
      - 6379:6379
