name: Translaterr.Transman.Api

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

env:
  DOCKERFILE: transman.api.dockerfile
  IMAGE_NAME: translaterr/transman.api

jobs:
  transman_api:
    name: "Translaterr.Transman.Api"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build solution
      run: docker build . --file $DOCKERFILE --target build --tag $IMAGE_NAME:${{ github.sha }}
    
    - name: Test solution
      run: docker build . --file $DOCKERFILE --target test --tag $IMAGE_NAME:${{ github.sha }}
    
    - name: Publish solution
      run: docker build . --file $DOCKERFILE --target runtime --tag $IMAGE_NAME:${{ github.sha }}
    
    - name: Dockerhub Login
      uses: docker/login-action@v1.6.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push image to dockerhub
      run: docker push $IMAGE_NAME:${{ github.sha }}
    
    - name: Tag latest Image
      if: github.ref == 'refs/heads/main'
      run: docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

    - name: Push latest Image
      run: docker push $IMAGE_NAME:latest
